### ISSUE TITLE
Do not wrap HTML comments in p-tags

### ISSUE THREAD

**Issue by exside** [coding-intl/micro-down#2]
First of all, amazing work you have done here!

Second I though it would probably be better to ignore HTML comments within the markdown text, for example I have an automatic TOC generator that will wrap the generated (nested) list into HTML comments, that will end up like this after parsing:

```html
<p><!-- TOC depthFrom:1 depthTo:4 withLinks:1 updateOnSave:1 orderedList:0 --></p>
```

not a big deal, but you'll get some extra spacing because of that.

**Comment by ShynRou** [comment]
Thanks.
I will add support for HTML comments, as it seems to me like a valid feature.

**Comment by ShynRou** [comment]
Thank you for your help! 
Just added comment support and published it all.

Install version 1.4.0 for comments, tabs, and html in pre-tags.
