### ISSUE TITLE
Link issue still happening v1.5.1

### ISSUE THREAD

**Issue by hipstersmoothie** [coding-intl/micro-down#9]
Given the link `https://en.wikipedia.org/wiki/Open_Financial_Exchange` I am still getting the following rendering

![screen shot 2018-10-19 at 10 28 19 am](https://user-images.githubusercontent.com/1192452/47234182-d5751300-d389-11e8-83ac-6080204792e1.png)

**Comment by ShynRou** [comment]
Fixed in 1.5.2 with commit 385b21f282c97d3d90eda9bba44859a3b7a5dfdf
